"""
Object storage offload for distill output.

When Cloudflare R2 is configured (see ``server.config.r2_configured``), each
generated APK/ZIP/mobileconfig is mirrored to R2 right after the local build
finishes. The download endpoint then 302-redirects clients to the public
CDN URL, so the VPS only pays for CPU during builds, not for download
bandwidth on every share/QR scan.

If R2 is not configured, every public function becomes a no-op and the
endpoint falls back to ``FileResponse`` against ``generated/<app_id>/...``.

R2 speaks the S3 API, which authenticates requests with AWS Signature V4.
Rather than pull in the heavy ``boto3``/``botocore`` stack (tens of MB) just
to talk to one bucket, we sign requests ourselves with the standard library
(:mod:`hmac`/:mod:`hashlib`) and send them over ``httpx`` — a dependency the
project already ships for its async HTTP needs. The signing implementation is
validated against AWS's published SigV4 test vectors (see ``tests``/self-test
in this module's ``__main__`` block).
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import hmac
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
from urllib.parse import quote, urlsplit

import httpx

from server import config


_MEDIA_BY_EXT = {
    ".apk": "application/vnd.android.package-archive",
    ".zip": "application/zip",
    ".gz": "application/gzip",
    ".tar": "application/x-tar",
    ".mobileconfig": "application/x-apple-aspen-config",
    ".png": "image/png",
    ".json": "application/json",
}

_EMPTY_PAYLOAD_SHA256 = hashlib.sha256(b"").hexdigest()
_SERVICE = "s3"
_REGION = "auto"  # R2 ignores region but SigV4 still requires one in the scope.
_ALGORITHM = "AWS4-HMAC-SHA256"


def _guess_content_type(path: Path) -> str:
    # tar.gz keeps the .gz extension when generated by the distiller; honour it
    # before falling back to a generic binary type.
    suffix = path.suffix.lower()
    return _MEDIA_BY_EXT.get(suffix, "application/octet-stream")


# --------------------------------------------------------------------------
# AWS Signature Version 4
#
# Reference: https://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html
# The functions below are intentionally framework-free so they can be unit
# tested against AWS's canonical example vectors.
# --------------------------------------------------------------------------
def _uri_encode(value: str, is_path: bool) -> str:
    """RFC 3986 percent-encoding as required by SigV4.

    ``quote`` never escapes the unreserved set (A-Z a-z 0-9 ``-._~``); for path
    components we additionally keep ``/`` literal (segment separators are not
    encoded), while query components encode everything else.
    """
    return quote(value, safe="/" if is_path else "")


def _hmac(key: bytes, msg: str) -> bytes:
    return hmac.new(key, msg.encode("utf-8"), hashlib.sha256).digest()


def _signing_key(secret: str, datestamp: str, region: str, service: str) -> bytes:
    k_date = _hmac(("AWS4" + secret).encode("utf-8"), datestamp)
    k_region = _hmac(k_date, region)
    k_service = _hmac(k_region, service)
    return _hmac(k_service, "aws4_request")


def _canonical_query_string(query_params: Optional[Dict[str, str]]) -> str:
    if not query_params:
        return ""
    parts = []
    for key in sorted(query_params):
        parts.append(f"{_uri_encode(key, False)}={_uri_encode(str(query_params[key]), False)}")
    return "&".join(parts)


def _sign_request(
    *,
    method: str,
    path: str,
    headers: Dict[str, str],
    payload_hash: str,
    access_key: str,
    secret_key: str,
    amz_date: str,
    datestamp: str,
    region: str = _REGION,
    service: str = _SERVICE,
    query_params: Optional[Dict[str, str]] = None,
) -> Dict[str, str]:
    """Return the headers (including ``Authorization``) for a signed request.

    ``headers`` must already contain everything that should be signed except
    ``x-amz-date`` and ``x-amz-content-sha256``, which are added here. Header
    names are matched case-insensitively and lower-cased for the canonical form.
    """
    signed = {k.lower(): str(v).strip() for k, v in headers.items()}
    signed["x-amz-date"] = amz_date
    signed["x-amz-content-sha256"] = payload_hash

    sorted_names = sorted(signed)
    canonical_headers = "".join(f"{name}:{signed[name]}\n" for name in sorted_names)
    signed_headers = ";".join(sorted_names)

    canonical_request = "\n".join(
        [
            method.upper(),
            _uri_encode(path, True),
            _canonical_query_string(query_params),
            canonical_headers,
            signed_headers,
            payload_hash,
        ]
    )

    scope = f"{datestamp}/{region}/{service}/aws4_request"
    string_to_sign = "\n".join(
        [
            _ALGORITHM,
            amz_date,
            scope,
            hashlib.sha256(canonical_request.encode("utf-8")).hexdigest(),
        ]
    )

    signature = hmac.new(
        _signing_key(secret_key, datestamp, region, service),
        string_to_sign.encode("utf-8"),
        hashlib.sha256,
    ).hexdigest()

    authorization = (
        f"{_ALGORITHM} Credential={access_key}/{scope}, "
        f"SignedHeaders={signed_headers}, Signature={signature}"
    )

    out = {name: signed[name] for name in signed}
    out["Authorization"] = authorization
    return out


class R2Storage:
    """Minimal S3/R2 client built on httpx + hand-rolled SigV4 signing."""

    def __init__(self):
        self._client: Optional[httpx.Client] = None

    @property
    def configured(self) -> bool:
        return config.r2_configured()

    def _http(self) -> httpx.Client:
        if self._client is None:
            # follow_redirects stays off: R2 endpoints never redirect, and a
            # signed request must not be silently replayed to another host.
            self._client = httpx.Client(timeout=httpx.Timeout(60.0, connect=10.0), follow_redirects=False)
        return self._client

    def _endpoint(self) -> str:
        endpoint = config.r2_endpoint_url()
        if not endpoint:
            raise RuntimeError("R2 endpoint is not configured (R2_ACCOUNT_ID missing).")
        return endpoint.rstrip("/")

    def _request(
        self,
        method: str,
        key: str,
        *,
        body: bytes = b"",
        content_type: Optional[str] = None,
        query_params: Optional[Dict[str, str]] = None,
    ) -> httpx.Response:
        """Sign and send one S3 request. ``key`` is the object key (no bucket).

        Path style is used: ``/<bucket>/<key>``. Returns the raw response; the
        caller decides how to interpret status codes.
        """
        endpoint = self._endpoint()
        host = urlsplit(endpoint).netloc
        bucket = config.r2_bucket()
        # Encode each path segment but keep the separators literal.
        encoded_key = "/".join(_uri_encode(part, False) for part in key.split("/"))
        path = f"/{bucket}"
        if encoded_key:
            path += f"/{encoded_key}"

        payload_hash = hashlib.sha256(body).hexdigest() if body else _EMPTY_PAYLOAD_SHA256
        now = _dt.datetime.now(_dt.timezone.utc)
        amz_date = now.strftime("%Y%m%dT%H%M%SZ")
        datestamp = now.strftime("%Y%m%d")

        base_headers: Dict[str, str] = {"host": host}
        if content_type:
            base_headers["content-type"] = content_type

        signed_headers = _sign_request(
            method=method,
            path=path,
            headers=base_headers,
            payload_hash=payload_hash,
            access_key=config.r2_access_key_id(),
            secret_key=config.r2_secret_access_key(),
            amz_date=amz_date,
            datestamp=datestamp,
            query_params=query_params,
        )

        # httpx provides Host itself from the URL; drop our signed copy so we
        # don't send a duplicate header (the signature already covers it).
        signed_headers.pop("host", None)

        url = f"{endpoint}{path}"
        return self._http().request(
            method,
            url,
            params=query_params or None,
            content=body,
            headers=signed_headers,
        )

    def public_url(self, key: str) -> Optional[str]:
        base = config.r2_public_base_url()
        if not base:
            return None
        return f"{base}/{key.lstrip('/')}"

    def upload_file(self, local_path: Path, key: str, content_type: Optional[str] = None) -> Optional[str]:
        """Upload a single file. Returns the public URL on success, else None."""
        if not self.configured:
            return None
        if not local_path.exists():
            return None
        body = local_path.read_bytes()
        resp = self._request(
            "PUT",
            key,
            body=body,
            content_type=content_type or _guess_content_type(local_path),
        )
        if resp.status_code not in (200, 201):
            raise RuntimeError(f"R2 PUT {key} failed: HTTP {resp.status_code} {resp.text[:200]}")
        return self.public_url(key)

    def upload_app_downloads(self, app_id: str, downloads_dir: Path) -> dict:
        """Upload every file in ``<app_id>/downloads/`` to R2.

        Returns a dict mapping filename -> public URL for the files that were
        successfully uploaded. Empty when storage is unconfigured.
        """
        if not self.configured or not downloads_dir.exists():
            return {}
        urls: dict = {}
        for path in sorted(downloads_dir.iterdir()):
            if not path.is_file():
                continue
            key = f"{app_id}/downloads/{path.name}"
            url = self.upload_file(path, key)
            if url:
                urls[path.name] = url
        return urls

    def delete_app(self, app_id: str) -> int:
        """Delete every object under ``<app_id>/`` (used during retention sweeps).

        Lists the prefix (paginating via the continuation token) and deletes
        each key with an individual DELETE. Generated apps hold only a handful
        of objects, so per-key deletes stay cheap and avoid the extra XML +
        Content-MD5 machinery a batch DeleteObjects request would need.
        """
        if not self.configured or not app_id:
            return 0
        prefix = f"{app_id}/"
        deleted = 0
        for key in self._list_keys(prefix):
            if self._delete_key(key):
                deleted += 1
        return deleted

    def _list_keys(self, prefix: str) -> Iterable[str]:
        continuation: Optional[str] = None
        while True:
            params = {"list-type": "2", "prefix": prefix, "max-keys": "1000"}
            if continuation:
                params["continuation-token"] = continuation
            resp = self._request("GET", "", query_params=params)
            if resp.status_code != 200:
                raise RuntimeError(
                    f"R2 ListObjectsV2 failed: HTTP {resp.status_code} {resp.text[:200]}"
                )
            keys, continuation = self._parse_list_response(resp.text)
            for key in keys:
                yield key
            if not continuation:
                break

    @staticmethod
    def _parse_list_response(xml_text: str) -> Tuple[List[str], Optional[str]]:
        """Extract object keys and the next continuation token from a
        ListObjectsV2 XML response (namespace-agnostic)."""
        try:
            root = ET.fromstring(xml_text)
        except ET.ParseError:
            return [], None

        def _local(tag: str) -> str:
            return tag.rsplit("}", 1)[-1]

        keys: List[str] = []
        next_token: Optional[str] = None
        is_truncated = False
        for elem in root:
            name = _local(elem.tag)
            if name == "Contents":
                for child in elem:
                    if _local(child.tag) == "Key" and child.text:
                        keys.append(child.text)
            elif name == "NextContinuationToken":
                next_token = (elem.text or "").strip() or None
            elif name == "IsTruncated":
                is_truncated = (elem.text or "").strip().lower() == "true"
        return keys, next_token if is_truncated else None

    def _delete_key(self, key: str) -> bool:
        resp = self._request("DELETE", key)
        # S3/R2 return 204 on success and also 204 when the key is already gone.
        if resp.status_code in (200, 204):
            return True
        raise RuntimeError(f"R2 DELETE {key} failed: HTTP {resp.status_code} {resp.text[:200]}")


# Module-level singleton — cheap because the httpx client is created lazily.
r2_storage = R2Storage()


# --------------------------------------------------------------------------
# Self-test: validate SigV4 against AWS's published example vector. Run with
# ``python -m server.engine.storage`` (no network, no credentials needed).
# --------------------------------------------------------------------------
def _self_test() -> None:
    # AWS S3 SigV4 reference: "GET Object" example from
    # https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html
    # This exercises the same code path real requests use, including the
    # required x-amz-content-sha256 header (added inside _sign_request).
    headers = _sign_request(
        method="GET",
        path="/test.txt",
        headers={
            "host": "examplebucket.s3.amazonaws.com",
            "range": "bytes=0-9",
        },
        payload_hash=_EMPTY_PAYLOAD_SHA256,
        access_key="AKIAIOSFODNN7EXAMPLE",
        secret_key="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
        amz_date="20130524T000000Z",
        datestamp="20130524",
        region="us-east-1",
        service="s3",
    )
    expected = "f0e8bdb87c964420e857bd35b5d6ed310bd44f0170aba48dd91039c6036bdb41"
    auth = headers["Authorization"]
    assert "SignedHeaders=host;range;x-amz-content-sha256;x-amz-date" in auth, auth
    assert f"Signature={expected}" in auth, f"SigV4 mismatch:\n{auth}"
    print("SigV4 S3 GET Object vector OK")
    print(auth)


if __name__ == "__main__":
    _self_test()
