"""
Object storage offload for distill output.

When Cloudflare R2 is configured (see ``server.config.r2_configured``), each
generated APK/ZIP/mobileconfig is mirrored to R2 right after the local build
finishes. The download endpoint then 302-redirects clients to the public
CDN URL, so the VPS only pays for CPU during builds, not for download
bandwidth on every share/QR scan.

If R2 is not configured, every public function becomes a no-op and the
endpoint falls back to ``FileResponse`` against ``generated/<app_id>/...``.

R2 uses S3 v4 signatures; we rely on ``boto3`` to avoid hand-rolling the
crypto. The client is lazily imported so the dependency is only required
when R2 is actually enabled.
"""

from __future__ import annotations

import threading
from pathlib import Path
from typing import Iterable, List, Optional

from server import config


_MEDIA_BY_EXT = {
    ".apk": "application/vnd.android.package-archive",
    ".zip": "application/zip",
    ".gz": "application/gzip",
    ".tar": "application/x-tar",
    ".mobileconfig": "application/x-apple-aspen-config",
    ".png": "image/png",
    ".json": "application/json",
}


def _guess_content_type(path: Path) -> str:
    # tar.gz keeps the .gz extension when generated by the distiller; honour it
    # before falling back to a generic binary type.
    suffix = path.suffix.lower()
    return _MEDIA_BY_EXT.get(suffix, "application/octet-stream")


class R2Storage:
    """Thin lazy wrapper around boto3's S3 client pointed at R2."""

    def __init__(self):
        self._client = None
        self._lock = threading.Lock()

    @property
    def configured(self) -> bool:
        return config.r2_configured()

    def _ensure_client(self):
        if self._client is not None:
            return self._client
        with self._lock:
            if self._client is not None:
                return self._client
            try:
                import boto3  # type: ignore
                from botocore.config import Config as BotoConfig  # type: ignore
            except ImportError as exc:
                raise RuntimeError(
                    "boto3 is required for R2 uploads. Run `pip install boto3` "
                    "or unset R2_* env vars to fall back to local downloads."
                ) from exc
            self._client = boto3.client(
                "s3",
                endpoint_url=config.r2_endpoint_url(),
                aws_access_key_id=config.r2_access_key_id(),
                aws_secret_access_key=config.r2_secret_access_key(),
                region_name="auto",
                config=BotoConfig(
                    signature_version="s3v4",
                    retries={"max_attempts": 3, "mode": "standard"},
                ),
            )
            return self._client

    def public_url(self, key: str) -> Optional[str]:
        base = config.r2_public_base_url()
        if not base:
            return None
        return f"{base}/{key.lstrip('/')}"

    def upload_file(self, local_path: Path, key: str, content_type: Optional[str] = None) -> Optional[str]:
        """Upload a single file. Returns the public URL on success, else None."""
        if not self.configured:
            return None
        if not local_path.exists():
            return None
        client = self._ensure_client()
        extra = {"ContentType": content_type or _guess_content_type(local_path)}
        client.upload_file(str(local_path), config.r2_bucket(), key, ExtraArgs=extra)
        return self.public_url(key)

    def upload_app_downloads(self, app_id: str, downloads_dir: Path) -> dict:
        """Upload every file in ``<app_id>/downloads/`` to R2.

        Returns a dict mapping filename -> public URL for the files that were
        successfully uploaded. Empty when storage is unconfigured.
        """
        if not self.configured or not downloads_dir.exists():
            return {}
        urls: dict = {}
        for path in sorted(downloads_dir.iterdir()):
            if not path.is_file():
                continue
            key = f"{app_id}/downloads/{path.name}"
            url = self.upload_file(path, key)
            if url:
                urls[path.name] = url
        return urls

    def delete_app(self, app_id: str) -> int:
        """Delete every object under ``<app_id>/`` (used during retention sweeps)."""
        if not self.configured or not app_id:
            return 0
        client = self._ensure_client()
        bucket = config.r2_bucket()
        prefix = f"{app_id}/"
        deleted = 0
        continuation = None
        while True:
            kwargs = {"Bucket": bucket, "Prefix": prefix, "MaxKeys": 1000}
            if continuation:
                kwargs["ContinuationToken"] = continuation
            page = client.list_objects_v2(**kwargs)
            objects = page.get("Contents") or []
            if objects:
                deleted += self._delete_keys(client, bucket, (obj["Key"] for obj in objects))
            if not page.get("IsTruncated"):
                break
            continuation = page.get("NextContinuationToken")
        return deleted

    @staticmethod
    def _delete_keys(client, bucket: str, keys: Iterable[str]) -> int:
        batch: List[dict] = []
        deleted = 0
        for key in keys:
            batch.append({"Key": key})
            if len(batch) >= 1000:
                deleted += R2Storage._flush_delete(client, bucket, batch)
                batch = []
        if batch:
            deleted += R2Storage._flush_delete(client, bucket, batch)
        return deleted

    @staticmethod
    def _flush_delete(client, bucket: str, batch: List[dict]) -> int:
        resp = client.delete_objects(Bucket=bucket, Delete={"Objects": batch, "Quiet": True})
        errors = resp.get("Errors") or []
        return len(batch) - len(errors)


# Module-level singleton — cheap because the inner boto3 client is itself lazy.
r2_storage = R2Storage()
